### ISSUE TITLE
Create a theme for pygments

### ISSUE THREAD

**Issue by zenorocha** [zenorocha/dracula-theme#61]
https://github.com/richleland/pygments-css

That way I can use it on Keynote with [Sublime Highlight](https://github.com/n1k0/SublimeHighlight/).

**Comment by zenorocha** [comment]
It took a veeeeery long time but I finally added it to this repo ;D

@Mottie would you mind sending a pull request to `site` branch with instructions on how to use it? Thanks!

**Comment by Mottie** [comment]
I'm really not sure what instructions would be needed here.

I've actually never used Sublime Highlight, but these definitions should be used to replace the pygments definitions in the resulting HTML file.

We were using this css to change the theme on GitHub code pages when they were still using pygments. To work with the Stylish browser addon, all definitions included an `!important` flag.

Anyway, I think that a `dracula.py` file should also be included (converted, but untested)

```python
# -*- coding: utf-8 -*-
"""
    Dracula Colorscheme
    ~~~~~~~~~~~~~~~~~~~

    Converted by Vim Colorscheme Converter
"""
from pygments.style import Style
from pygments.token import Token, Operator, Keyword, Name, Generic, Comment, Number, String

class DraculaStyle(Style):

    background_color = '#282a36'
    styles = {
        Token:              'noinherit #f8f8f2 bg:#282a36',
        Name.Function:      'noinherit #50fa7b',
        Name.Label:         'noinherit #f1fa8c',
        Generic.Heading:    '#f8f8f2 bold',
        Name.Attribute:     'noinherit #50fa7b',
        Operator.Word:      'noinherit #ff79c6',
        Name.Entity:        'noinherit #f8f8f2',
        Generic.Emph:       'underline',
        Generic.Subheading: '#f8f8f2 bold',
        Comment:            'noinherit #6272a4',
        Name.Variable:      'noinherit #8be9fd italic',
        String:             'noinherit #f1fa8c',
        Keyword:            'noinherit #ff79c6',
        Generic.Deleted:    'noinherit #8b080b',
        Keyword.Type:       'noinherit #8be9fd',
        Name.Constant:      'noinherit',
        Comment.Preproc:    'noinherit #ff79c6',
        Generic.Output:     'noinherit #525563 bg:#282a36',
        Name.Tag:           'noinherit #ff79c6',
        Number.Float:       'noinherit #bd93f9',
        Generic.Inserted:   '#f8f8f2 bg:#468410 bold',
        Number:             'noinherit #bd93f9',
        Generic.Traceback:  'noinherit #f8f8f0 bg:#ff79c6',
    }
```

**Comment by cbracco** [comment]
@zenorocha @Mottie Funny, I was actually building a dracula pygments for a personal project. Here is a slightly cleaned up version, I’d be happy to integrate it.

```css
.highlight {
  background-color: #282a36;
  color: #f8f8f2;
}

.highlight .hll {
  background-color: #ffffcc;
}

/* Comment */
.highlight .c {
  color: #6272a4;
}

/* Error */
.highlight .err {
  color: #f8f8f2;
}

/* Escape */
.highlight .esc {
  color: #f8f8f2;
}

/* Generic */
.highlight .g {
  color: #f8f8f2;
}

/* Keyword */
.highlight .k {
  color: #ff79c6;
}

/* Literal */
.highlight .l {
  color: #f8f8f2;
}

/* Name */
.highlight .n {
  color: #f8f8f2;
}

/* Operator */
.highlight .o {
  color: #ff79c6;
}

/* Other */
.highlight .x {
  color: #f8f8f2;
}

/* Punctuation */
.highlight .p {
  color: #f8f8f2;
}

/* Comment.Hashbang */
.highlight .ch {
  color: #6272a4;
}

/* Comment.Multiline */
.highlight .cm {
  color: #6272a4;
}

/* Comment.Preproc */
.highlight .cp {
  color: #ff79c6;
}

/* Comment.PreprocFile */
.highlight .cpf {
  color: #6272a4;
}

/* Comment.Single */
.highlight .c1 {
  color: #6272a4;
}

/* Comment.Special */
.highlight .cs {
  color: #6272a4;
}

/* Generic.Deleted */
.highlight .gd {
  color: #8b080b;
}

/* Generic.Emph */
.highlight .ge {
  color: #f8f8f2;
  text-decoration: underline;
}

/* Generic.Error */
.highlight .gr {
  color: #f8f8f2;
}

/* Generic.Heading */
.highlight .gh {
  color: #f8f8f2;
  font-weight: bold;
}

/* Generic.Inserted */
.highlight .gi {
  color: #f8f8f2;
  font-weight: bold;
}

/* Generic.Output */
.highlight .go {
  color: #525563;
}

/* Generic.Prompt */
.highlight .gp {
  color: #f8f8f2;
}

/* Generic.Strong */
.highlight .gs {
  color: #f8f8f2;
}

/* Generic.Subheading */
.highlight .gu {
  color: #f8f8f2;
  font-weight: bold;
}

/* Generic.Traceback */
.highlight .gt {
  color: #f8f8f0;
}

/* Keyword.Constant */
.highlight .kc {
  color: #ff79c6;
}

/* Keyword.Declaration */
.highlight .kd {
  color: #8be9fd;
  font-style: italic;
}

/* Keyword.Namespace */
.highlight .kn {
  color: #ff79c6;
}

/* Keyword.Pseudo */
.highlight .kp {
  color: #ff79c6;
}

/* Keyword.Reserved */
.highlight .kr {
  color: #ff79c6;
}

/* Keyword.Type */
.highlight .kt {
  color: #8be9fd;
}

/* Literal.Date */
.highlight .ld {
  color: #f8f8f2;
}

/* Literal.Number */
.highlight .m {
  color: #bd93f9;
}

/* Literal.String */
.highlight .s {
  color: #f1fa8c;
}

/* Name.Attribute */
.highlight .na {
  color: #50fa7b;
}

/* Name.Builtin */
.highlight .nb {
  color: #f8f8f2;
}

/* Name.Class */
.highlight .nc {
  color: #50fa7b;
}

/* Name.Constant */
.highlight .no {
  color: #f8f8f2;
}

/* Name.Decorator */
.highlight .nd {
  color: #f8f8f2;
}

/* Name.Entity */
.highlight .ni {
  color: #f8f8f2;
}

/* Name.Exception */
.highlight .ne {
  color: #f8f8f2;
}

/* Name.Function */
.highlight .nf {
  color: #50fa7b;
}

/* Name.Label */
.highlight .nl {
  color: #8be9fd;
  font-style: italic;
}

/* Name.Namespace */
.highlight .nn {
  color: #f8f8f2;
}

/* Name.Other */
.highlight .nx {
  color: #f8f8f2;
}

/* Name.Property */
.highlight .py {
  color: #f8f8f2;
}

/* Name.Tag */
.highlight .nt {
  color: #ff79c6;
}

/* Name.Variable */
.highlight .nv {
  color: #8be9fd;
  font-style: italic;
}

/* Operator.Word */
.highlight .ow {
  color: #ff79c6;
}

/* Text.Whitespace */
.highlight .w {
  color: #f8f8f2;
}

/* Literal.Number.Bin */
.highlight .mb {
  color: #bd93f9;
}

/* Literal.Number.Float */
.highlight .mf {
  color: #bd93f9;
}

/* Literal.Number.Hex */
.highlight .mh {
  color: #bd93f9;
}

/* Literal.Number.Integer */
.highlight .mi {
  color: #bd93f9;
}

/* Literal.Number.Oct */
.highlight .mo {
  color: #bd93f9;
}

/* Literal.String.Affix */
.highlight .sa {
  color: #f1fa8c;
}

/* Literal.String.Backtick */
.highlight .sb {
  color: #f1fa8c;
}

/* Literal.String.Char */
.highlight .sc {
  color: #f1fa8c;
}

/* Literal.String.Delimiter */
.highlight .dl {
  color: #f1fa8c;
}

/* Literal.String.Doc */
.highlight .sd {
  color: #f1fa8c;
}

/* Literal.String.Double */
.highlight .s2 {
  color: #f1fa8c;
}

/* Literal.String.Escape */
.highlight .se {
  color: #f1fa8c;
}

/* Literal.String.Heredoc */
.highlight .sh {
  color: #f1fa8c;
}

/* Literal.String.Interpol */
.highlight .si {
  color: #f1fa8c;
}

/* Literal.String.Other */
.highlight .sx {
  color: #f1fa8c;
}

/* Literal.String.Regex */
.highlight .sr {
  color: #f1fa8c;
}

/* Literal.String.Single */
.highlight .s1 {
  color: #f1fa8c;
}

/* Literal.String.Symbol */
.highlight .ss {
  color: #f1fa8c;
}

/* Name.Builtin.Pseudo */
.highlight .bp {
  color: #f8f8f2;
}

/* Name.Function.Magic */
.highlight .fm {
  color: #50fa7b;
}

/* Name.Variable.Class */
.highlight .vc {
  color: #8be9fd;
  font-style: italic;
}

/* Name.Variable.Global */
.highlight .vg {
  color: #8be9fd;
  font-style: italic;
}

/* Name.Variable.Instance */
.highlight .vi {
  color: #8be9fd;
  font-style: italic;
}

/* Name.Variable.Magic */
.highlight .vm {
  color: #8be9fd;
  font-style: italic;
}

/* Literal.Number.Integer.Long */
.highlight .il {
  color: #bd93f9;
}
```
