### ISSUE TITLE
Give Highlight.js "a bite"? :)

### ISSUE THREAD

**Issue by IngwiePhoenix** [zenorocha/dracula-theme#97]
Hey,

I sadly don't exactly know how to make an easy HighlightJS theme. But would it be possible for anyone in the team to make one? That would be really nice since I work in Atom and display on the web using HighlightJS.

Kind regards, Ingwie!

**Comment by zenorocha** [comment]
Hey @IngwiePhoenix,

I don't know Highlight.JS as well but I'd love to see a Dracula theme for that.

**Comment by dciccale** [comment]
try this theme i just made

save the following css into `dracula.css`

```css
.hljs {
  display: block;
  overflow-x: auto;
  padding: 0.5em;
  background: #282a36;
}

.hljs-keyword,
.hljs-selector-tag,
.hljs-literal,
.hljs-section,
.hljs-link {
  color: #8be9fd;
}

.hljs-function .hljs-keyword {
  color: #ff79c6;
}

.hljs,
.hljs-subst {
  color: #f8f8f2;
}

.hljs-string,
.hljs-title,
.hljs-name,
.hljs-type,
.hljs-attribute,
.hljs-symbol,
.hljs-bullet,
.hljs-addition,
.hljs-variable,
.hljs-template-tag,
.hljs-template-variable {
  color: #f1fa8c;
}

.hljs-comment,
.hljs-quote,
.hljs-deletion,
.hljs-meta {
  color: #6272a4;
}

.hljs-keyword,
.hljs-selector-tag,
.hljs-literal,
.hljs-title,
.hljs-section,
.hljs-doctag,
.hljs-type,
.hljs-name,
.hljs-strong {
  font-weight: bold;
}

.hljs-emphasis {
  font-style: italic;
}
```

save the following html into `demo.html` and open to see the result

```html
<!doctype html>
<link rel="stylesheet" href="dracula.css">

<pre><code class="javascript">
addEventListener('load', function() {
  var code = document.querySelector('#code');
  var worker = new Worker('worker.js');
  worker.onmessage = function(event) { code.innerHTML = event.data; }
  worker.postMessage(code.textContent);
});
</code></pre>

<script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.1.0/highlight.min.js"></script>
<script>hljs.initHighlightingOnLoad();</script>
```
